### PR TITLE
feat(gcloud): Add support for external account authentication

### PR DESCRIPTION
**Pull request by zzztimbo**
This change adds support for external account authentication (workload identity federation) for the Google Cloud client. This allows the client to authenticate using external identity providers, such as AWS IAM roles, instead of relying on the traditional Application Default Credentials flow.

The changes include:

1. Adding a new function `try_external_account_authenticator()` to attempt to generate an `ExternalAccountAuthenticator` using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
2. Updating the `get_authenticator()` function to try the external account authenticator if the other methods (service account, user credentials, instance metadata) fail.
3. Improving the error messages to provide more context when the authenticator generation fails.

These changes provide more flexibility in how the Google Cloud client can authenticate, making it easier to use in different environments and reducing the reliance on the traditional Application Default Credentials flow.

Here are some specifics about the format of the external account format: https://github.com/buildkite-plugins/gcp-workload-identity-federation-buildkite-plugin/blob/main/hooks/environment#L50-L64

### CODE REVIEW

**Comment by PierreBeucher** [comment]
Thanks for this PR ! I'll review it ASAP to give feedback or merge right away

**Comment by PierreBeucher** [comment]
Code LGTM, thanks for the detailed explanation :) 

Small question: I thought that the `GOOGLE_APPLICATION_CREDENTIALS` variable normally used by Application Default Credentials (ADC, implemented as `ApplicationDefaultCredentialsAuthenticator` in `yup-oauth2`) also worked for Workload Identity Federation as documented on https://cloud.google.com/docs/authentication/application-default-credentials), isn't that the case or I missed something ?
  - EDIT: reading `yup-oauth2`  code and doc again it seems ADC is not fully implemented so it answers my question.

I'll merge right after I tested with an AWS or Azure IAM external access.

**Comment by zzztimbo** [comment]
@PierreBeucher is there anything I can do to help move this along?

**Comment by PierreBeucher** [comment]
I was "under the water" as we say in my country sorry. Will probably do that in the next few days, you did well to remind me.

**Comment by PierreBeucher** [comment]
Well, setting up Workload Identity Federation on my testing account was quite a ride - but hey, works like a charm ! There it goes, I'll add a bit of testing and release soon ;)

Thanks again for all of this

**Comment by PierreBeucher** [comment]
Added a small test requiring (lots of) setup: https://github.com/PierreBeucher/novops/pull/138

**Pull request merged**
